version: "3.9"

services:
  app:
    image: YOUR_DOCKER_USERNAME/devops-cicd-prod:latest
    container_name: devops_app
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
