name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/devops-cicd-prod
          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${{ github.sha }}

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/devops-cicd-prod
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-cicd-prod:latest
            docker stop devops_app || true
            docker rm devops_app || true
            docker run -d -p 80:3000 \
              --name devops_app \
              -e NODE_ENV=production \
              ${{ secrets.DOCKER_USERNAME }}/devops-cicd-prod:latest
